# Generated by Django 5.1.6 on 2025-02-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
