# Generated by Django 5.1.6 on 2025-02-17 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="is_favorite",
            new_name="is_favourite",
        ),
    ]
